//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "incidents", table_name = "activity_log")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub event_type: String,
    pub incident_id: Option<i32>,
    pub ban_id: Option<i32>,
    #[sea_orm(column_type = "JsonBinary")]
    pub event_data: Json,
    pub created_at: DateTimeWithTimeZone,
    pub org_unit: Option<Uuid>,
    pub actor_id: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::attachments::Entity")]
    Attachments,
    #[sea_orm(has_many = "super::external_link::Entity")]
    ExternalLink,
    #[sea_orm(has_many = "super::generated_ban_letter::Entity")]
    GeneratedBanLetter,
    #[sea_orm(
        belongs_to = "super::incidents::Entity",
        from = "Column::IncidentId",
        to = "super::incidents::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Incidents,
    #[sea_orm(
        belongs_to = "super::patron_ban::Entity",
        from = "Column::BanId",
        to = "super::patron_ban::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    PatronBan,
}

impl Related<super::attachments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Attachments.def()
    }
}

impl Related<super::external_link::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ExternalLink.def()
    }
}

impl Related<super::generated_ban_letter::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GeneratedBanLetter.def()
    }
}

impl Related<super::incidents::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Incidents.def()
    }
}

impl Related<super::patron_ban::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PatronBan.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
