//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "incidents", table_name = "attachments")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub incident_id: Option<i32>,
    pub activity_log_id: Option<i64>,
    pub file_upload: Option<Uuid>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::activity_log::Entity",
        from = "Column::ActivityLogId",
        to = "super::activity_log::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    ActivityLog,
    #[sea_orm(
        belongs_to = "super::incidents::Entity",
        from = "Column::IncidentId",
        to = "super::incidents::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Incidents,
}

impl Related<super::activity_log::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ActivityLog.def()
    }
}

impl Related<super::incidents::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Incidents.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
