//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "incidents", table_name = "ban_letter_template")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub subject: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub body: String,
    pub is_default: bool,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text", nullable)]
    pub name: Option<String>,
    pub is_trespass: bool,
    #[sea_orm(column_type = "Text")]
    pub operation_type: String,
    pub created_by: Uuid,
    pub deleted_by: Option<Uuid>,
    pub updated_by: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::generated_ban_letter::Entity")]
    GeneratedBanLetter,
}

impl Related<super::generated_ban_letter::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GeneratedBanLetter.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
