//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "incidents", table_name = "external_link")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique_key = "idx_external_link_unique_incident_url")]
    pub incident: Option<i32>,
    #[sea_orm(
        column_type = "Text",
        unique_key = "idx_external_link_unique_activity_log_url"
    )]
    pub url: String,
    #[sea_orm(column_type = "Text")]
    pub title: String,
    pub link_type: Option<i32>,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub restricted_access: bool,
    pub added_at: DateTimeWithTimeZone,
    #[sea_orm(unique_key = "idx_external_link_unique_activity_log_url")]
    pub activity_log_id: Option<i64>,
    pub added_by: Option<Uuid>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::activity_log::Entity",
        from = "Column::ActivityLogId",
        to = "super::activity_log::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    ActivityLog,
    #[sea_orm(
        belongs_to = "super::external_link_type::Entity",
        from = "Column::LinkType",
        to = "super::external_link_type::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ExternalLinkType,
    #[sea_orm(
        belongs_to = "super::incidents::Entity",
        from = "Column::Incident",
        to = "super::incidents::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Incidents,
}

impl Related<super::activity_log::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ActivityLog.def()
    }
}

impl Related<super::external_link_type::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ExternalLinkType.def()
    }
}

impl Related<super::incidents::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Incidents.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
