//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "incidents", table_name = "generated_ban_letter")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub ban: i32,
    pub template: Option<i32>,
    #[sea_orm(column_type = "Text")]
    pub content: String,
    pub generated_at: DateTimeWithTimeZone,
    pub activity_log_id: Option<i64>,
    pub incident: Option<i32>,
    pub generated_by_org: Option<Uuid>,
    pub generated_by: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::activity_log::Entity",
        from = "Column::ActivityLogId",
        to = "super::activity_log::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    ActivityLog,
    #[sea_orm(
        belongs_to = "super::ban_letter_template::Entity",
        from = "Column::Template",
        to = "super::ban_letter_template::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    BanLetterTemplate,
    #[sea_orm(
        belongs_to = "super::incidents::Entity",
        from = "Column::Incident",
        to = "super::incidents::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Incidents,
    #[sea_orm(
        belongs_to = "super::patron_ban::Entity",
        from = "Column::Ban",
        to = "super::patron_ban::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    PatronBan,
}

impl Related<super::activity_log::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ActivityLog.def()
    }
}

impl Related<super::ban_letter_template::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BanLetterTemplate.def()
    }
}

impl Related<super::incidents::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Incidents.def()
    }
}

impl Related<super::patron_ban::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PatronBan.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
