//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "incidents", table_name = "incident_template_map")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique_key = "chk_template_once_per_incident")]
    pub incident: i32,
    #[sea_orm(unique_key = "chk_template_once_per_incident")]
    pub template: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::incidents::Entity",
        from = "Column::Incident",
        to = "super::incidents::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Incidents,
    #[sea_orm(
        belongs_to = "super::templates::Entity",
        from = "Column::Template",
        to = "super::templates::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Templates,
}

impl Related<super::incidents::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Incidents.def()
    }
}

impl Related<super::templates::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Templates.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
