//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "incidents", table_name = "incident_review")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub incident: i32,
    pub reviewed_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "Text")]
    pub result: String,
    pub min_review_level: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub comments: Option<String>,
    pub reviewed_by: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::incidents::Entity",
        from = "Column::Incident",
        to = "super::incidents::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Incidents,
}

impl Related<super::incidents::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Incidents.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
