//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "incidents", table_name = "incidents")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub sub_location: Option<i32>,
    pub title: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub metadata: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub custom_fields: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub ai_analysis: Option<Json>,
    pub emergency_capture: Option<bool>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
    pub resolved_at: Option<DateTimeWithTimeZone>,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub called_emergency: Option<bool>,
    pub occurred_at: DateTimeWithTimeZone,
    pub org_unit: Uuid,
    pub created_by: Uuid,
    pub resolved_by: Option<Uuid>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::activity_log::Entity")]
    ActivityLog,
    #[sea_orm(has_many = "super::attachments::Entity")]
    Attachments,
    #[sea_orm(has_many = "super::external_link::Entity")]
    ExternalLink,
    #[sea_orm(has_many = "super::generated_ban_letter::Entity")]
    GeneratedBanLetter,
    #[sea_orm(has_many = "super::incident_links::Entity")]
    IncidentLinks,
    #[sea_orm(has_many = "super::incident_review::Entity")]
    IncidentReview,
    #[sea_orm(has_many = "super::incident_template_map::Entity")]
    IncidentTemplateMap,
    #[sea_orm(has_many = "super::involved_parties::Entity")]
    InvolvedParties,
    #[sea_orm(has_many = "super::migration_attachment::Entity")]
    MigrationAttachment,
    #[sea_orm(has_many = "super::patron_ban::Entity")]
    PatronBan,
    #[sea_orm(has_many = "super::resolution_checklists::Entity")]
    ResolutionChecklists,
    #[sea_orm(
        belongs_to = "super::sub_locations::Entity",
        from = "Column::SubLocation",
        to = "super::sub_locations::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    SubLocations,
}

impl Related<super::activity_log::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ActivityLog.def()
    }
}

impl Related<super::attachments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Attachments.def()
    }
}

impl Related<super::external_link::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ExternalLink.def()
    }
}

impl Related<super::generated_ban_letter::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GeneratedBanLetter.def()
    }
}

impl Related<super::incident_links::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IncidentLinks.def()
    }
}

impl Related<super::incident_review::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IncidentReview.def()
    }
}

impl Related<super::incident_template_map::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IncidentTemplateMap.def()
    }
}

impl Related<super::involved_parties::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::InvolvedParties.def()
    }
}

impl Related<super::migration_attachment::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MigrationAttachment.def()
    }
}

impl Related<super::patron_ban::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PatronBan.def()
    }
}

impl Related<super::resolution_checklists::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ResolutionChecklists.def()
    }
}

impl Related<super::sub_locations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SubLocations.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
