//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "incidents", table_name = "migration_attachment")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub incident: i32,
    pub patron: i32,
    #[sea_orm(unique)]
    pub external_id: i32,
    pub created_at: DateTimeWithTimeZone,
    pub files_imported_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::incidents::Entity",
        from = "Column::Incident",
        to = "super::incidents::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Incidents,
    #[sea_orm(
        belongs_to = "super::patrons::Entity",
        from = "Column::Patron",
        to = "super::patrons::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Patrons,
}

impl Related<super::incidents::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Incidents.def()
    }
}

impl Related<super::patrons::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Patrons.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
