//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub mod prelude;

pub mod activity_log;
pub mod attachments;
pub mod ban_letter_template;
pub mod categories;
pub mod external_link;
pub mod external_link_type;
pub mod generated_ban_letter;
pub mod incident_links;
pub mod incident_review;
pub mod incident_template_map;
pub mod incidents;
pub mod involved_parties;
pub mod merge_history;
pub mod migration_attachment;
pub mod notification_email_routing;
pub mod patron_age_range;
pub mod patron_ban;
pub mod patron_notes;
pub mod patron_photo;
pub mod patron_timeline_events;
pub mod patrons;
pub mod quick_access_locations;
pub mod resolution_checklists;
pub mod review_chain;
pub mod review_group;
pub mod review_group_member;
pub mod sub_locations;
pub mod templates;
