//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "incidents", table_name = "patron_photo")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub patron: i32,
    pub is_primary: bool,
    pub file_upload: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::patrons::Entity",
        from = "Column::Patron",
        to = "super::patrons::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Patrons,
}

impl Related<super::patrons::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Patrons.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
