//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "incidents", table_name = "patron_notes")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub patron_id: i32,
    pub note_type: String,
    #[sea_orm(column_type = "Text")]
    pub content: String,
    pub incident_id: Option<i32>,
    pub visibility: Option<String>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub created_by: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::patrons::Entity",
        from = "Column::PatronId",
        to = "super::patrons::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Patrons,
}

impl Related<super::patrons::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Patrons.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
