//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "incidents", table_name = "patrons")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub library_card: Option<String>,
    pub first_name: String,
    pub middle_name: Option<String>,
    pub last_name: String,
    pub preferred_name: Option<String>,
    pub phone: Option<String>,
    pub email: Option<String>,
    pub address_line1: Option<String>,
    pub address_line2: Option<String>,
    pub city: Option<String>,
    pub state_province: Option<String>,
    pub postal_code: Option<String>,
    pub country: Option<String>,
    pub photo_url: Option<String>,
    pub identification_type: Option<String>,
    pub identification_number: Option<String>,
    pub risk_level: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub notes: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub metadata: Option<Json>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text")]
    pub display_name: String,
    pub is_unknown: bool,
    pub age_range: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub alias: Option<String>,
    pub created_by: Option<Uuid>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::merge_history::Entity")]
    MergeHistory,
    #[sea_orm(has_many = "super::migration_attachment::Entity")]
    MigrationAttachment,
    #[sea_orm(
        belongs_to = "super::patron_age_range::Entity",
        from = "Column::AgeRange",
        to = "super::patron_age_range::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    PatronAgeRange,
    #[sea_orm(has_many = "super::patron_ban::Entity")]
    PatronBan,
    #[sea_orm(has_many = "super::patron_notes::Entity")]
    PatronNotes,
    #[sea_orm(has_one = "super::patron_photo::Entity")]
    PatronPhoto,
    #[sea_orm(has_many = "super::patron_timeline_events::Entity")]
    PatronTimelineEvents,
}

impl Related<super::merge_history::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MergeHistory.def()
    }
}

impl Related<super::migration_attachment::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MigrationAttachment.def()
    }
}

impl Related<super::patron_age_range::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PatronAgeRange.def()
    }
}

impl Related<super::patron_ban::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PatronBan.def()
    }
}

impl Related<super::patron_notes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PatronNotes.def()
    }
}

impl Related<super::patron_photo::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PatronPhoto.def()
    }
}

impl Related<super::patron_timeline_events::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PatronTimelineEvents.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
