//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "incidents", table_name = "patron_ban")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub patron: i32,
    pub incident: i32,
    pub starts_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "Text", nullable)]
    pub comments: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub is_trespass: bool,
    pub archives_at: Option<DateTimeWithTimeZone>,
    pub lifts_at: DateTimeWithTimeZone,
    pub org_unit: Uuid,
    pub archived_by: Option<Uuid>,
    pub created_by: Uuid,
    pub lifted_by: Option<Uuid>,
    pub updated_by: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::activity_log::Entity")]
    ActivityLog,
    #[sea_orm(has_many = "super::generated_ban_letter::Entity")]
    GeneratedBanLetter,
    #[sea_orm(
        belongs_to = "super::incidents::Entity",
        from = "Column::Incident",
        to = "super::incidents::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Incidents,
    #[sea_orm(
        belongs_to = "super::patrons::Entity",
        from = "Column::Patron",
        to = "super::patrons::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Patrons,
}

impl Related<super::activity_log::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ActivityLog.def()
    }
}

impl Related<super::generated_ban_letter::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GeneratedBanLetter.def()
    }
}

impl Related<super::incidents::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Incidents.def()
    }
}

impl Related<super::patrons::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Patrons.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
