//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "incidents", table_name = "quick_access_locations")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub sub_location_id: Option<i32>,
    pub custom_name: Option<String>,
    pub display_order: Option<i32>,
    pub usage_count: Option<i32>,
    pub last_used_at: Option<DateTimeWithTimeZone>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub org_unit: Uuid,
    pub user_id: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::sub_locations::Entity",
        from = "Column::SubLocationId",
        to = "super::sub_locations::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    SubLocations,
}

impl Related<super::sub_locations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SubLocations.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
