//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "incidents", table_name = "resolution_checklists")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub incident_id: i32,
    #[sea_orm(column_type = "JsonBinary")]
    pub checklist_items: Json,
    #[sea_orm(column_type = "JsonBinary")]
    pub completed_items: Json,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::incidents::Entity",
        from = "Column::IncidentId",
        to = "super::incidents::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Incidents,
}

impl Related<super::incidents::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Incidents.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
