//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "incidents", table_name = "review_group")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub name: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub org_unit: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::review_chain::Entity")]
    ReviewChain,
    #[sea_orm(has_many = "super::review_group_member::Entity")]
    ReviewGroupMember,
}

impl Related<super::review_chain::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ReviewChain.def()
    }
}

impl Related<super::review_group_member::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ReviewGroupMember.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
