//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "incidents", table_name = "review_chain")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique_key = "review_chain_org_unit_review_level_key")]
    pub review_level: i32,
    pub reviewer_group: i32,
    pub is_final: bool,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub require_peer_review: bool,
    #[sea_orm(unique_key = "review_chain_org_unit_review_level_key")]
    pub org_unit: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::review_group::Entity",
        from = "Column::ReviewerGroup",
        to = "super::review_group::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ReviewGroup,
}

impl Related<super::review_group::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ReviewGroup.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
