//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "incidents", table_name = "shift_note_conduct_area")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub shift_note: i32,
    pub conduct_area: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::shift_note::Entity",
        from = "Column::ShiftNote",
        to = "super::shift_note::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    ShiftNote,
    #[sea_orm(
        belongs_to = "super::config_shift_note_conduct_area::Entity",
        from = "Column::ConductArea",
        to = "super::config_shift_note_conduct_area::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ConfigShiftNoteConductArea,
}

impl Related<super::shift_note::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ShiftNote.def()
    }
}

impl Related<super::config_shift_note_conduct_area::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ConfigShiftNoteConductArea.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
