//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "incidents", table_name = "shift_note")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    /// Where it happened. No FK into org.unit — see the db-decoupling TODO in
    /// sqitch migration 101.
    pub org_unit: Uuid,
    pub r#type: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub patron_name: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub patron_description: Option<String>,
    pub was_instructed: bool,
    pub was_warned: bool,
    #[sea_orm(column_type = "Text")]
    pub notes: String,
    pub occurred_at: DateTimeWithTimeZone,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: Option<DateTimeWithTimeZone>,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    /// No FK into auth.usr — see the db-decoupling TODO in migration 101.
    pub created_by: Uuid,
    pub updated_by: Option<Uuid>,
    pub deleted_by: Option<Uuid>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::config_shift_note_type::Entity",
        from = "Column::Type",
        to = "super::config_shift_note_type::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ConfigShiftNoteType,
}

impl Related<super::config_shift_note_type::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ConfigShiftNoteType.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
