//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "incidents", table_name = "sub_locations")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub label: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub code: Option<String>,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub org_unit: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::incidents::Entity")]
    Incidents,
    #[sea_orm(has_many = "super::quick_access_locations::Entity")]
    QuickAccessLocations,
}

impl Related<super::incidents::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Incidents.def()
    }
}

impl Related<super::quick_access_locations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::QuickAccessLocations.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
