//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(schema_name = "incidents", table_name = "templates")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub category: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub fields: Json,
    pub is_active: Option<bool>,
    pub version: Option<i32>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub requires_patron: bool,
    pub show_called_emergency: bool,
    pub created_by: Option<Uuid>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::categories::Entity",
        from = "Column::Category",
        to = "super::categories::Column::Code",
        on_update = "Cascade",
        on_delete = "NoAction"
    )]
    Categories,
    #[sea_orm(has_many = "super::incident_template_map::Entity")]
    IncidentTemplateMap,
}

impl Related<super::categories::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Categories.def()
    }
}

impl Related<super::incident_template_map::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IncidentTemplateMap.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
